package com.chart.model;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chart.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chart.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chart.score
     *
     * @mbggenerated
     */
    private Integer score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chart.id
     *
     * @return the value of chart.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chart.id
     *
     * @param id the value for chart.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chart.name
     *
     * @return the value of chart.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chart.name
     *
     * @param name the value for chart.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chart.score
     *
     * @return the value of chart.score
     *
     * @mbggenerated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chart.score
     *
     * @param score the value for chart.score
     *
     * @mbggenerated
     */
    public void setScore(Integer score) {
        this.score = score;
    }
    
    @Override
    public String toString() {
    	// TODO Auto-generated method stub
    	return "name:"+name+"score"+score;
    }
}